export const STORAGE_KEYS = {
  highScore: "skyCircuits.highScore.v1",
  telemetry: "skyCircuits.telemetry.v1",
};

export const FIXED_DT = 1 / 60;

export const GAME_CONFIG = {
  progression: {
    scorePerEnvironment: 50,
    transitionDuration: 0.9,
    labelDuration: 1.35,
  },
  environments: [
    {
      id: "stratos-labs",
      label: "Stratos Labs",
      backgroundSprite: "bg-phase-1.png",
      pipeBodySprite: "pipe-body-phase-1.png",
      pipeCapSprite: "pipe-cap-phase-1.png",
      backgroundFallback: {
        top: "#8fd5ff",
        mid: "#4ca9f4",
        bottom: "#1e69bb",
      },
      hud: {
        panel: "rgba(8, 31, 64, 0.73)",
        stroke: "rgba(176, 241, 255, 0.82)",
        text: "#ecffff",
        textSoft: "#bdeeff",
        progressTrack: "rgba(6, 20, 54, 0.72)",
        progressStroke: "rgba(167, 247, 255, 0.82)",
        progressStart: "#3cd6ff",
        progressEnd: "#78ffd8",
        heatLabel: "#f3feff",
        overheat: "#ff4d4d",
      },
      collectible: {
        outer: "#f8ff87",
        inner: "#ffdb3d",
      },
      pipeFallback: {
        bodyStart: "#1a4e88",
        bodyMid: "#28d8ff",
        bodyEnd: "#0f2d58",
        finStart: "#ffbb56",
        finEnd: "#ffd99a",
        capStart: "#1f6ab0",
        capEnd: "#103968",
        rim: "#071a35",
      },
      phaseBadge: {
        bg: "rgba(11, 45, 81, 0.78)",
        border: "rgba(161, 241, 255, 0.88)",
        text: "#d8fbff",
      },
    },
    {
      id: "ember-foundry",
      label: "Ember Foundry",
      backgroundSprite: "bg-phase-2.png",
      pipeBodySprite: "pipe-body-phase-2.png",
      pipeCapSprite: "pipe-cap-phase-2.png",
      backgroundFallback: {
        top: "#ffbe67",
        mid: "#df7b2f",
        bottom: "#7d3d20",
      },
      hud: {
        panel: "rgba(61, 24, 7, 0.72)",
        stroke: "rgba(255, 199, 142, 0.86)",
        text: "#fff3e5",
        textSoft: "#ffdcb6",
        progressTrack: "rgba(54, 20, 7, 0.74)",
        progressStroke: "rgba(255, 212, 171, 0.9)",
        progressStart: "#ffb55f",
        progressEnd: "#ffe392",
        heatLabel: "#fff2e8",
        overheat: "#ffd27d",
      },
      collectible: {
        outer: "#ffe89b",
        inner: "#ffb84a",
      },
      pipeFallback: {
        bodyStart: "#6a3518",
        bodyMid: "#f0a145",
        bodyEnd: "#3a1f10",
        finStart: "#ffd195",
        finEnd: "#ffecbf",
        capStart: "#8a4b20",
        capEnd: "#4f2a13",
        rim: "#2b1409",
      },
      phaseBadge: {
        bg: "rgba(72, 30, 10, 0.78)",
        border: "rgba(255, 210, 158, 0.92)",
        text: "#fff5e8",
      },
    },
    {
      id: "ion-storm",
      label: "Ion Storm",
      backgroundSprite: "bg-phase-3.png",
      pipeBodySprite: "pipe-body-phase-3.png",
      pipeCapSprite: "pipe-cap-phase-3.png",
      backgroundFallback: {
        top: "#174785",
        mid: "#0c2f65",
        bottom: "#040f2d",
      },
      hud: {
        panel: "rgba(5, 18, 42, 0.78)",
        stroke: "rgba(123, 239, 255, 0.84)",
        text: "#e4fbff",
        textSoft: "#9feaff",
        progressTrack: "rgba(4, 13, 31, 0.82)",
        progressStroke: "rgba(105, 243, 255, 0.9)",
        progressStart: "#39cbef",
        progressEnd: "#69ffff",
        heatLabel: "#e8fcff",
        overheat: "#ff6f5a",
      },
      collectible: {
        outer: "#9ff7ff",
        inner: "#3bddff",
      },
      pipeFallback: {
        bodyStart: "#0d223f",
        bodyMid: "#56ddff",
        bodyEnd: "#061022",
        finStart: "#8ff8ff",
        finEnd: "#d3ffff",
        capStart: "#12355e",
        capEnd: "#07152f",
        rim: "#030a18",
      },
      phaseBadge: {
        bg: "rgba(6, 22, 49, 0.8)",
        border: "rgba(112, 246, 255, 0.9)",
        text: "#ddfcff",
      },
    },
  ],
  physics: {
    gravity: 1200,
    flapImpulse: -420,
    maxFallSpeed: 620,
    fluxGravityMultiplier: 0.72,
    overheatGravityMultiplier: 1.2,
    groundBounceDamping: 0.12,
  },
  player: {
    radius: 16,
    hitboxRadiusXFactor: 0.72,
    hitboxRadiusYFactor: 0.8,
    hitboxOffsetX: -1,
    baseXFactor: 0.28,
    maxXFactor: 0.75,
    horizontalSpring: 3.2,
    horizontalDrag: 5.5,
    fluxPush: 320,
    invulnerabilityAfterShield: 0.35,
  },
  powerUps: {
    maxCharges: 2,
    heatPerUse: 30,
    heatDissipationPerSec: 21,
    overheatThreshold: 100,
    overheatDuration: 2.1,
    pool: [
      { type: "shield", label: "Pulse Shield", duration: 1.35, weight: 0.36 },
      { type: "gap", label: "Gap Widen", duration: 1.85, weight: 0.34 },
      { type: "flux", label: "Flux Boost", duration: 0.95, weight: 0.3 },
    ],
  },
  spawn: {
    obstacleWidthMin: 70,
    obstacleWidthMax: 96,
    obstacleSpacingMin: 225,
    edgeMargin: 24,
    collectibleRadius: 12,
    collectibleBonus: 2,
  },
  difficulty: {
    phase1: {
      until: 20,
      obstacleSpeed: 180,
      spawnInterval: 1.55,
      gapHeight: 192,
      collectibleChance: 0.58,
    },
    phase2: {
      until: 45,
      obstacleSpeed: 220,
      spawnInterval: 1.32,
      gapHeight: 170,
      collectibleChance: 0.66,
    },
    phase3: {
      until: Number.POSITIVE_INFINITY,
      obstacleSpeed: 258,
      spawnInterval: 1.08,
      gapHeight: 154,
      collectibleChance: 0.74,
    },
  },
};
